### ISSUE TITLE
error when running python -m robocasa.demos.demo_tasks

### ISSUE THREAD

**Issue by AbdElrahmanMostafaRifaat1432** [robocasa/robocasa#110]
Choose an option 0 to 13, or any other key for default (PnPCounterToCab): 0
Initializing environment for PnPCounterToCab...
[robosuite INFO] Loading controller configuration from: C:\Users\abdelrahman.rifaat\AppData\Local\anaconda3\envs\Robocasa\Lib\site-packages\robosuite\controllers\config\robots\default_pandaomron.json (composite_controller_factory.py:121)

Playing back episode: demo_8
Instruction: pick the liquor from the counter and place it in the cabinet
Spawning environment...
Traceback (most recent call last):
  File "C:\Users\abdelrahman.rifaat\AppData\Local\anaconda3\envs\robocasa\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\abdelrahman.rifaat\AppData\Local\anaconda3\envs\robocasa\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\abdelrahman.rifaat\AppData\Local\anaconda3\envs\Robocasa\Lib\site-packages\robocasa\demos\demo_tasks.py", line 148, in <module>
    playback_dataset(parser)
  File "C:\Users\abdelrahman.rifaat\AppData\Local\anaconda3\envs\Robocasa\Lib\site-packages\robocasa\scripts\playback_dataset.py", line 395, in playback_dataset
    playback_trajectory_with_env(
  File "C:\Users\abdelrahman.rifaat\AppData\Local\anaconda3\envs\Robocasa\Lib\site-packages\robocasa\scripts\playback_dataset.py", line 61, in playback_trajectory_with_env
    reset_to(env, initial_state)
  File "C:\Users\abdelrahman.rifaat\AppData\Local\anaconda3\envs\Robocasa\Lib\site-packages\robocasa\scripts\playback_dataset.py", line 239, in reset_to
    env.reset()
  File "C:\Users\abdelrahman.rifaat\AppData\Local\anaconda3\envs\Robocasa\Lib\site-packages\robosuite\environments\base.py", line 270, in reset
    self._load_model()
  File "C:\Users\abdelrahman.rifaat\AppData\Local\anaconda3\envs\Robocasa\Lib\site-packages\robocasa\environments\kitchen\kitchen.py", line 463, in _load_model
    self._create_objects()
  File "C:\Users\abdelrahman.rifaat\AppData\Local\anaconda3\envs\Robocasa\Lib\site-packages\robocasa\environments\kitchen\kitchen.py", line 497, in _create_objects
    model, info = self._create_obj(cfg)
  File "C:\Users\abdelrahman.rifaat\AppData\Local\anaconda3\envs\Robocasa\Lib\site-packages\robocasa\environments\kitchen\kitchen.py", line 573, in _create_obj
    object_kwargs, object_info = self.sample_object(
  File "C:\Users\abdelrahman.rifaat\AppData\Local\anaconda3\envs\Robocasa\Lib\site-packages\robocasa\environments\kitchen\kitchen.py", line 1450, in sample_object
    return sample_kitchen_object(
  File "C:\Users\abdelrahman.rifaat\AppData\Local\anaconda3\envs\Robocasa\Lib\site-packages\robocasa\models\objects\kitchen_object_utils.py", line 208, in sample_kitchen_object
    mjcf_kwargs, info = sample_kitchen_object_helper(
  File "C:\Users\abdelrahman.rifaat\AppData\Local\anaconda3\envs\Robocasa\Lib\site-packages\robocasa\models\objects\kitchen_object_utils.py", line 326, in sample_kitchen_object_helper
    raise ValueError
ValueError

**Comment by snasiriany** [comment]
Hi, did you download all of the assets?

From installation page here: https://robocasa.ai/docs/introduction/installation.html
python robocasa/scripts/download_kitchen_assets.py
