### ISSUE TITLE
ValueError: probabilities contain NaN

### ISSUE THREAD

**Issue by sachinb20** [robocasa/robocasa#64]
Im facing this issue when running the following demo task:
python -m robocasa.demos.demo_tasks

[robosuite WARNING] No private macro file found! (macros.py:53)
[robosuite WARNING] It is recommended to use a private macro file (macros.py:54)
[robosuite WARNING] To setup, run: python /home/dell/robosuite/robosuite/scripts/setup_macros.py (macros.py:55)
WARNING: mimicgen environments not imported since mimicgen is not installed!
Tasks:
[0] PnPCounterToCab: pick and place from counter to cabinet
[1] PnPCounterToSink: pick and place from counter to sink
[2] PnPMicrowaveToCounter: pick and place from microwave to counter
[3] PnPStoveToCounter: pick and place from stove to counter
[4] OpenSingleDoor: open cabinet or microwave door
[5] CloseDrawer: close drawer
[6] TurnOnMicrowave: turn on microwave
[7] TurnOnSinkFaucet: turn on sink faucet
[8] TurnOnStove: turn on stove
[9] ArrangeVegetables: arrange vegetables on a cutting board
[10] MicrowaveThawing: place frozen food in microwave for thawing
[11] RestockPantry: restock cans in pantry
[12] PreSoakPan: prepare pan for washing
[13] PrepareCoffee: make coffee

Choose an option 0 to 13, or any other key for default (PnPCounterToCab): 1
Initializing environment for PnPCounterToSink...
/home/dell/robocasa/robocasa/models/objects/kitchen_objects.py:2505: RuntimeWarning: invalid value encountered in divide
  p=np.array([len(choices[reg]) for reg in obj_registries])
Traceback (most recent call last):
  File "/home/dell/miniconda3/envs/robocasa/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dell/miniconda3/envs/robocasa/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dell/robocasa/robocasa/demos/demo_tasks.py", line 148, in <module>
    playback_dataset(parser)
  File "/home/dell/robocasa/robocasa/scripts/playback_dataset.py", line 336, in playback_dataset
    env = robosuite.make(**env_kwargs)
  File "/home/dell/robosuite/robosuite/environments/base.py", line 41, in make
    return REGISTERED_ENVS[env_name](*args, **kwargs)
  File "/home/dell/robocasa/robocasa/environments/kitchen/single_stage/kitchen_pnp.py", line 268, in __init__
    super().__init__(obj_groups=obj_groups, *args, **kwargs)
  File "/home/dell/robocasa/robocasa/environments/kitchen/single_stage/kitchen_pnp.py", line 18, in __init__
    super().__init__(*args, **kwargs)
  File "/home/dell/robocasa/robocasa/environments/kitchen/kitchen.py", line 286, in __init__
    super().__init__(
  File "/home/dell/robosuite/robosuite/environments/manipulation/manipulation_env.py", line 184, in __init__
    super().__init__(
  File "/home/dell/robosuite/robosuite/environments/robot_env.py", line 227, in __init__
    super().__init__(
  File "/home/dell/robosuite/robosuite/environments/base.py", line 144, in __init__
    self._load_model()
  File "/home/dell/robocasa/robocasa/environments/kitchen/kitchen.py", line 467, in _load_model
    model, info = _create_obj(cfg)
  File "/home/dell/robocasa/robocasa/environments/kitchen/kitchen.py", line 434, in _create_obj
    object_kwargs, object_info = self.sample_object(
  File "/home/dell/robocasa/robocasa/environments/kitchen/kitchen.py", line 1337, in sample_object
    return sample_kitchen_object(
  File "/home/dell/robocasa/robocasa/models/objects/kitchen_objects.py", line 2309, in sample_kitchen_object
    mjcf_kwargs, info = sample_kitchen_object_helper(
  File "/home/dell/robocasa/robocasa/models/objects/kitchen_objects.py", line 2503, in sample_kitchen_object_helper
    chosen_reg = rng.choice(
  File "_generator.pyx", line 743, in numpy.random._generator.Generator.choice
ValueError: probabilities contain NaN

**Comment by snasiriany** [comment]
Interesting issue. I was unable to reproduce this error. It seems perhaps the object assets are not properly installed.

You can check by running:
```
find robocasa/models/assets/objects/objaverse -type f -name "*.xml" -print | wc -l
```

You should see 914 printed. If not, try to download the assets again by running `python robocasa/scripts/download_kitchen_assets.py`
