### ISSUE TITLE
Script Not Completing when Running `dataset_states_to_obs.py`

### ISSUE THREAD

**Issue by KysonYoshi** [robocasa/robocasa#84]
Hi,

I want to generate a video that explores the kitchen scene, so I decided to use `collect_demos.py.` However, I ecountered an issue with the script `dataset_states_to_obs.py`. When processing a dataset in RoboCasa, the script does not complete as expected and seems to hang, without returning control back to the command line.
### Step to Reproduce:
1. collect.demos.py line 119 
```
discard_traj = True
```
adjust to 
```
#discard_traj = True
```
Since I need a video that goes through the kitchen scene.
2. 
```
python robocasa/scripts/collect_demos.py --env PnPCounterToCab --device keyboard
```
3. 
```
python robomimic/scripts/conversion/convert_robosuite.py --dataset <ds-path>
```
4.
```
OMP_NUM_THREADS=1 MPI_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 python robomimic/scripts/dataset_states_to_obs.py --dataset <ds-path>
```
The script starts running, but it never finishes or returns to the (robocasa) prompt. The following appears:
```
  (robocasa) cl6933@LAPTOP-QEKOMNA4:~/robocasa$ OMP_NUM_THREADS=1 MPI_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 python /home/cl6933/robomimic/robomimic/scripts/dataset_states_to_obs.py --dataset /home/cl6933/robocasa/robocasa/models/assets/demonstrations_private/2024-10-02-20-36-12/demotest.hdf5
  ROBOMIMIC WARNING(
      No private macro file found!
      It is recommended to use a private macro file
      To setup, run: python /home/cl6933/robomimic/robomimic/scripts/setup_macros.py
  )
  input file: /home/cl6933/robocasa/robocasa/models/assets/demonstrations_private/2024-10-02-20-36-12/demotest.hdf5
  output file: /home/cl6933/robocasa/robocasa/models/assets/demonstrations_private/2024-10-02-20-36-12/demotest_im128.hdf5
  WARNING: mimicgen environments not imported since mimicgen is not installed!

  ============= Initialized Observation Utils with Obs Spec =============

  using obs modality: low_dim with keys: []
  using obs modality: rgb with keys: ['robot0_eye_in_hand_image', 'robot0_agentview_right_image', 'robot0_agentview_left_image']
  WARNING: mimicgen environments not imported since mimicgen is not installed!

  ============= Initialized Observation Utils with Obs Spec =============

  using obs modality: low_dim with keys: []
  using obs modality: rgb with keys: ['robot0_eye_in_hand_image', 'robot0_agentview_right_image', 'robot0_agentview_left_image']
  WARNING: mimicgen environments not imported since mimicgen is not installed!

  ============= Initialized Observation Utils with Obs Spec =============

  using obs modality: low_dim with keys: []
  using obs modality: rgb with keys: ['robot0_eye_in_hand_image', 'robot0_agentview_right_image', 'robot0_agentview_left_image']
  WARNING: mimicgen environments not imported since mimicgen is not installed!

  ============= Initialized Observation Utils with Obs Spec =============

  using obs modality: low_dim with keys: []
  using obs modality: rgb with keys: ['robot0_eye_in_hand_image', 'robot0_agentview_right_image', 'robot0_agentview_left_image']
  WARNING: mimicgen environments not imported since mimicgen is not installed!

  ============= Initialized Observation Utils with Obs Spec =============

  using obs modality: low_dim with keys: []
  using obs modality: rgb with keys: ['robot0_eye_in_hand_image', 'robot0_agentview_right_image', 'robot0_agentview_left_image']
  libEGL warning: failed to open /dev/dri/renderD128: Permission denied

  libEGL warning: failed to open /dev/dri/renderD128: Permission denied

  libEGL warning: NEEDS EXTENSION: falling back to kms_swrast
  libEGL warning: failed to open /dev/dri/renderD128: Permission denied

  libEGL warning: failed to open /dev/dri/renderD128: Permission denied

  libEGL warning: failed to open /dev/dri/renderD128: Permission denied

  libEGL warning: failed to open /dev/dri/renderD128: Permission denied

  libEGL warning: NEEDS EXTENSION: falling back to kms_swrast
  libEGL warning: NEEDS EXTENSION: falling back to kms_swrast
  libEGL warning: failed to open /dev/dri/renderD128: Permission denied

  libEGL warning: failed to open /dev/dri/renderD128: Permission denied

  libEGL warning: NEEDS EXTENSION: falling back to kms_swrast
  libEGL warning: failed to open /dev/dri/renderD128: Permission denied

  libEGL warning: failed to open /dev/dri/renderD128: Permission denied

  libEGL warning: NEEDS EXTENSION: falling back to kms_swrast
  ==== Using environment with the following metadata ====
  {
      "env_name": "PnPCounterToCab",
      "env_version": "1.5.0",
      "type": 1,
      "env_kwargs": {
          "robots": "PandaMobile",
          "controller_configs": {
              "type": "OSC_POSE",
              "input_max": 1,
              "input_min": -1,
              "output_max": [
                  0.05,
                  0.05,
                  0.05,
                  0.5,
                  0.5,
                  0.5
              ],
              "output_min": [
                  -0.05,
                  -0.05,
                  -0.05,
                  -0.5,
                  -0.5,
                  -0.5
              ],
              "kp": 150,
              "damping_ratio": 1,
              "impedance_mode": "fixed",
              "kp_limits": [
                  0,
                  300
              ],
              "damping_ratio_limits": [
                  0,
                  10
              ],
              "position_limits": null,
              "orientation_limits": null,
              "uncouple_pos_ori": true,
              "control_delta": true,
              "interpolation": null,
              "ramp_ratio": 0.2
          },
          "layout_ids": -1,
          "style_ids": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              11
          ],
          "translucent_robot": false,
          "obj_instance_split": "A",
          "reward_shaping": false,
          "camera_names": [
              "robot0_agentview_left",
              "robot0_agentview_right",
              "robot0_eye_in_hand"
          ],
          "camera_heights": 128,
          "camera_widths": 128,
          "has_renderer": false,
          "has_offscreen_renderer": true,
          "ignore_done": true,
          "use_object_obs": true,
          "use_camera_obs": true,
          "camera_depths": false
      }
  }

  ==== Using environment with the following metadata ====
  {
      "env_name": "PnPCounterToCab",
      "env_version": "1.5.0",
      "type": 1,
      "env_kwargs": {
          "robots": "PandaMobile",
          "controller_configs": {
              "type": "OSC_POSE",
              "input_max": 1,
              "input_min": -1,
              "output_max": [
                  0.05,
                  0.05,
                  0.05,
                  0.5,
                  0.5,
                  0.5
              ],
              "output_min": [
                  -0.05,
                  -0.05,
                  -0.05,
                  -0.5,
                  -0.5,
                  -0.5
              ],
              "kp": 150,
              "damping_ratio": 1,
              "impedance_mode": "fixed",
              "kp_limits": [
                  0,
                  300
              ],
              "damping_ratio_limits": [
                  0,
                  10
              ],
              "position_limits": null,
              "orientation_limits": null,
              "uncouple_pos_ori": true,
              "control_delta": true,
              "interpolation": null,
              "ramp_ratio": 0.2
          },
          "layout_ids": -1,
          "style_ids": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              11
          ],
          "translucent_robot": false,
          "obj_instance_split": "A",
          "reward_shaping": false,
          "camera_names": [
              "robot0_agentview_left",
              "robot0_agentview_right",
              "robot0_eye_in_hand"
          ],
          "camera_heights": 128,
          "camera_widths": 128,
          "has_renderer": false,
          "has_offscreen_renderer": true,
          "ignore_done": true,
          "use_object_obs": true,
          "use_camera_obs": true,
          "camera_depths": false
      }
  }

  Process 4 finished
  Process 2 finished
  ==== Using environment with the following metadata ====
  {
      "env_name": "PnPCounterToCab",
      "env_version": "1.5.0",
      "type": 1,
      "env_kwargs": {
          "robots": "PandaMobile",
          "controller_configs": {
              "type": "OSC_POSE",
              "input_max": 1,
              "input_min": -1,
              "output_max": [
                  0.05,
                  0.05,
                  0.05,
                  0.5,
                  0.5,
                  0.5
              ],
              "output_min": [
                  -0.05,
                  -0.05,
                  -0.05,
                  -0.5,
                  -0.5,
                  -0.5
              ],
              "kp": 150,
              "damping_ratio": 1,
              "impedance_mode": "fixed",
              "kp_limits": [
                  0,
                  300
              ],
              "damping_ratio_limits": [
                  0,
                  10
              ],
              "position_limits": null,
              "orientation_limits": null,
              "uncouple_pos_ori": true,
              "control_delta": true,
              "interpolation": null,
              "ramp_ratio": 0.2
          },
          "layout_ids": -1,
          "style_ids": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              11
          ],
          "translucent_robot": false,
          "obj_instance_split": "A",
          "reward_shaping": false,
          "camera_names": [
              "robot0_agentview_left",
              "robot0_agentview_right",
              "robot0_eye_in_hand"
          ],
          "camera_heights": 128,
          "camera_widths": 128,
          "has_renderer": false,
          "has_offscreen_renderer": true,
          "ignore_done": true,
          "use_object_obs": true,
          "use_camera_obs": true,
          "camera_depths": false
      }
  }

  Process 1 finished
```

### Evironment:
- OS: Windows WSL Ubuntu-24.04
- Python: 3.10
- numpy: 1.23.2
- Robominic: robomimic -b robocasa

**Comment by snasiriany** [comment]
Do you know how many demos are you in `demotest.hdf5`? One possible suspicion is that the number of demos might be small in this case, leading to some unexpected issues. I wonder if you run the script in step 4 with `--num_procs 1` whether the issue goes away.

**Comment by KysonYoshi** [comment]
Thank you for the solution. My demo.hdf5 file contains only one demonstration. After running the script from step 4 with `--num_procs 1`, the script was able to complete execution and returned control back to the command line. However, a new issue has arisen: when I try to access the im128.hdf5 dataset, it appears to be empty.

```
import h5py
import json

f = h5py.File(INSERT_DATASET_PATH)
demo = f["data"]["demo_1"]                        
obs = demo["obs"]                                 
left_img = obs["robot0_agentview_left_image"][:]  
ep_meta = json.loads(demo.attrs["ep_meta"])       
lang = ep_meta["lang"]                            
f.close()
```

```
Traceback (most recent call last):
  File "/home/cl6933/robocasa/show_replay.py", line 5, in <module>
    demo = f["data"]["demo_1"]                        # access demo 5
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/cl6933/miniconda3/envs/robocasa/lib/python3.10/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 241, in h5py.h5o.open
KeyError: "Unable to synchronously open object (object 'demo_1' doesn't exist)"
```

```
import h5py
import json

f = h5py.File(INSERT_DATASET_PATH)
demo = f["data"]                     
print(demo)                           
f.close()
```

```
<HDF5 group "/data" (0 members)>
```

**Comment by snasiriany** [comment]
I think this is due to some issues with the multi core version of the dataset_states_to_obs.py script. We have an older version of this that using a single core: https://github.com/ARISE-Initiative/robomimic/blob/robocasa/robomimic/scripts/deprecated/single_core_dataset_states_to_obs.py

It's slightly deprecated now, but if you try this, does it at least successfully extract that single demo that you have?

**Comment by kylekam** [comment]
> Thank you for the solution. My demo.hdf5 file contains only one demonstration. After running the script from step 4 with `--num_procs 1`, the script was able to complete execution and returned control back to the command line. However, a new issue has arisen: when I try to access the im128.hdf5 dataset, it appears to be empty.
> 
> ```
> import h5py
> import json
> 
> f = h5py.File(INSERT_DATASET_PATH)
> demo = f["data"]["demo_1"]                        
> obs = demo["obs"]                                 
> left_img = obs["robot0_agentview_left_image"][:]  
> ep_meta = json.loads(demo.attrs["ep_meta"])       
> lang = ep_meta["lang"]                            
> f.close()
> ```
> 
> ```
> Traceback (most recent call last):
>   File "/home/cl6933/robocasa/show_replay.py", line 5, in <module>
>     demo = f["data"]["demo_1"]                        # access demo 5
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "/home/cl6933/miniconda3/envs/robocasa/lib/python3.10/site-packages/h5py/_hl/group.py", line 357, in __getitem__
>     oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5o.pyx", line 241, in h5py.h5o.open
> KeyError: "Unable to synchronously open object (object 'demo_1' doesn't exist)"
> ```
> 
> ```
> import h5py
> import json
> 
> f = h5py.File(INSERT_DATASET_PATH)
> demo = f["data"]                     
> print(demo)                           
> f.close()
> ```
> 
> ```
> <HDF5 group "/data" (0 members)>
> ```

I am currently experiencing the same issue.
