### ISSUE TITLE
[Bug] ImportError: cannot import name 'sample_kitchen_object' from 'robocasa.models.objects.kitchen_objects' 

### ISSUE THREAD

**Issue by StoneT2000** [robocasa/robocasa#94]
```
python -m robocasa.demos.demo_objects
[robosuite WARNING] No private macro file found! (macros.py:53)
[robosuite WARNING] It is recommended to use a private macro file (macros.py:54)
[robosuite WARNING] To setup, run: python /home/stao/work/external/robosuite/robosuite/scripts/setup_macros.py (macros.py:55)
WARNING: mimicgen environments not imported since mimicgen is not installed!
Traceback (most recent call last):
  File "/home/stao/miniforge3/envs/robocasa/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/stao/miniforge3/envs/robocasa/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/stao/work/external/robocasa/robocasa/demos/demo_objects.py", line 22, in <module>
    from robocasa.models.objects.kitchen_objects import sample_kitchen_object
ImportError: cannot import name 'sample_kitchen_object' from 'robocasa.models.objects.kitchen_objects' (/home/stao/work/external/robocasa/robocasa/models/objects/kitchen_objects.py)
```

It seems the function is missing

**Comment by snasiriany** [comment]
This was due to a recent refactoring operation that we did. Fixed with a commit I just pushed to `main` branch: https://github.com/robocasa/robocasa/commit/370f986aa3934be6c134ecb978952423df9a1ed0

Thanks!
